# Generated by Django 4.0.1 on 2022-01-26 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birth_date_alter_user_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 54, 57, 374246)),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 54, 57, 374322), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 54, 57, 374352), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 54, 57, 374266)),
        ),
    ]
