# Generated by Django 4.0.1 on 2022-01-26 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_survey_created_on_alter_user_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 55, 50, 514250)),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 55, 50, 514323), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 55, 50, 514352), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 55, 50, 514268)),
        ),
    ]
