# Generated by Django 4.0.1 on 2022-01-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='do_not_disturb',
            field=models.BooleanField(default=False),
        ),
    ]
