# Generated by Django 4.0.1 on 2022-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_dnd_dnd_user_id_dnd_email_dnd_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnd',
            name='phone_number',
            field=models.CharField(default=None, max_length=12, null=True, unique=True),
        ),
    ]
