# Generated by Django 4.0.1 on 2022-02-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnd',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dnd',
            name='username',
        ),
        migrations.AddField(
            model_name='dnd',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
